services:
  - type: web
    name: dlx-translation-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: TOKEN
        sync: false
